# Generated by Django 4.1.2 on 2023-01-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorapplication',
            old_name='job',
            new_name='job_name',
        ),
        migrations.RemoveField(
            model_name='contractorapplication',
            name='name',
        ),
    ]
